#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/dangxq/springcloud/
#          search-paths: config-center/config-repo
#          username:
#          password:
#      label: master
# ---native
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

server:
  port: 9001
##指定服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

#management:
#  security:
#    enabled: false
