eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: customer-ribbon
    api-b:
      path: /api-b/**
      serviceId: customer-feign
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 6000