server:
  port: 9003
spring:
  datasource:
    name: springboot
    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
---
mybatis:
 mapper-locations: classpath:mapping/*.xml
 type-aliases-package: com.jason.service.user.model
# 打印sql
logging:
  level:
    com.jason.service.user.mapper : debug