#logging:
#  level:
#    org.springframework.security: INFO

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
spring:
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#  actuator:
#    enabled: true
#    sensitive: false
#  beans:
#    sensitive: false
#    enabled: true


management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true


