spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dangxq/springcloud/
          search-paths: config-repo
          username:
          password:
      label: master
server:
  port: 8888