spring:
  application:
    name: zipkin-server
  cloud:
    config:
      label: master
      profile: pro
      discovery:
        enabled: true
        service-id: config-server

management:
  metrics:
    web:
      server:
        auto-time-requests: false